<<<<<<< HEAD
server_enable_disable: false
amount_bootstrap: 0
bind_addr: "{{ansible_eth1.ipv4.address}}"
server_ip : "192.168.2.15"
=======
server_ip : "192.168.2.15"
server_enable: false
amount_bootstrap: 0
bind_addr: "{{ansible_eth1.ipv4.address}}"
>>>>>>> 6f84b6658cc24fc08532515905d8b9151a7e7f30
